export interface ClubTeam {
  name: string;
  division: string;
}

export interface Club {
  name: string;
  venue: string;
  location: string;
  lat: number;
  lng: number;
  teams: ClubTeam[];
}

// Group all teams by their actual club/venue location
export const clubs: Club[] = [
  {
    name: "Hei",
    venue: "Mortens Plass KG",
    location: "Skien",
    lat: 59.08838,
    lng: 9.68080,
    teams: [
      { name: "Hei", division: "4. divisjon" },
      { name: "Hei 2", division: "5. divisjon" },
      { name: "Hei 3", division: "7. divisjon" },
    ],
  },
  {
    name: "Langangen",
    venue: "Myrhaug stadion",
    location: "Langangen",
    lat: 59.08267,
    lng: 9.80952,
    teams: [{ name: "Langangen", division: "4. divisjon" }],
  },
  {
    name: "Eidanger",
    venue: "Eidangerbanen KG",
    location: "Eidanger",
    lat: 59.11544,
    lng: 9.69604,
    teams: [
      { name: "Eidanger", division: "4. divisjon" },
      { name: "Eidanger 2", division: "5. divisjon" },
    ],
  },
  {
    name: "Odd",
    venue: "Skagerak Arena",
    location: "Skien",
    lat: 59.21151,
    lng: 9.58986,
    teams: [
      { name: "Odd 3", division: "4. divisjon" },
      { name: "Odd 2 kvinner", division: "4. div kvinner" },
    ],
  },
  {
    name: "Urædd",
    venue: "Urædd KG / Kjølnes",
    location: "Porsgrunn",
    lat: 59.14167,
    lng: 9.66643,
    teams: [
      { name: "Urædd", division: "4. divisjon" },
      { name: "Urædd 2", division: "5. divisjon" },
      { name: "Urædd 3", division: "7. divisjon" },
      { name: "Urædd kvinner", division: "4. div kvinner" },
    ],
  },
  {
    name: "Storm",
    venue: "Bratsberg KG",
    location: "Bratsberg",
    lat: 59.20429,
    lng: 9.62406,
    teams: [
      { name: "Storm", division: "4. divisjon" },
      { name: "Storm 2", division: "5. divisjon" },
      { name: "Storm 3", division: "7. divisjon" },
      { name: "Fossum/Storm kvinner", division: "4. div kvinner" },
    ],
  },
  {
    name: "Tollnes",
    venue: "Tollnes Stadion KG",
    location: "Skien",
    lat: 59.16105,
    lng: 9.62841,
    teams: [
      { name: "Tollnes", division: "4. divisjon" },
      { name: "Tollnes kvinner", division: "4. div kvinner" },
    ],
  },
  {
    name: "Notodden / Snøgg",
    venue: "Idrettsparken / Notodden KG",
    location: "Notodden",
    lat: 59.56364,
    lng: 9.25984,
    teams: [
      { name: "Notodden 2", division: "4. divisjon" },
      { name: "Snøgg", division: "5. divisjon" },
      { name: "Snøgg kvinner", division: "4. div kvinner" },
    ],
  },
  {
    name: "Brevik",
    venue: "Furulund KG",
    location: "Brevik",
    lat: 59.05617,
    lng: 9.69432,
    teams: [
      { name: "Brevik", division: "4. divisjon" },
      { name: "Brevik 2", division: "6. divisjon" },
    ],
  },
  {
    name: "Gulset",
    venue: "Gulset KG",
    location: "Skien",
    lat: 59.21169,
    lng: 9.55546,
    teams: [
      { name: "Gulset", division: "4. divisjon" },
      { name: "Gulset 2", division: "7. divisjon" },
    ],
  },
  {
    name: "Skarphedin",
    venue: "Sandvoll / Telemarkshallen KG",
    location: "Bø i Telemark",
    lat: 59.41802,
    lng: 9.07809,
    teams: [
      { name: "Skarphedin", division: "4. divisjon" },
      { name: "Skarphedin 2", division: "7. divisjon" },
      { name: "Skarphedin kvinner", division: "4. div kvinner" },
    ],
  },
  {
    name: "Stathelle/Langesund",
    venue: "Bunes KG",
    location: "Stathelle",
    lat: 59.03696,
    lng: 9.70568,
    teams: [{ name: "Stathelle/Langesund", division: "4. divisjon" }],
  },
  {
    name: "Sannidal",
    venue: "Kolbånn KG",
    location: "Sannidal",
    lat: 58.90143,
    lng: 9.31200,
    teams: [
      { name: "Sannidal", division: "5. divisjon" },
      { name: "Sannidal 2", division: "7. divisjon" },
    ],
  },
  {
    name: "Skidar",
    venue: "Helges Plass KG",
    location: "Skien",
    lat: 59.19427,
    lng: 9.62885,
    teams: [{ name: "Skidar", division: "5. divisjon" }],
  },
  {
    name: "Skiens Grane",
    venue: "Granebanen KG",
    location: "Skien",
    lat: 59.20065,
    lng: 9.59477,
    teams: [{ name: "Skiens Grane", division: "5. divisjon" }],
  },
  {
    name: "Herkules",
    venue: "Herkules KG",
    location: "Skien",
    lat: 59.18246,
    lng: 9.59941,
    teams: [
      { name: "Herkules", division: "5. divisjon" },
      { name: "Herkules kvinner", division: "4. div kvinner" },
    ],
  },
  {
    name: "Langesund/Stathelle",
    venue: "Slåttenes KG",
    location: "Langesund",
    lat: 59.00000,
    lng: 9.74279,
    teams: [{ name: "Langesund/Stathelle", division: "5. divisjon" }],
  },
  {
    name: "Kroken",
    venue: "Sandvann stadion",
    location: "Neslandsvatn",
    lat: 58.93230,
    lng: 9.12725,
    teams: [{ name: "Kroken", division: "5. divisjon" }],
  },
  {
    name: "Kragerø",
    venue: "Kragerø Stadion KG",
    location: "Kragerø",
    lat: 58.87111,
    lng: 9.40673,
    teams: [{ name: "Kragerø", division: "5. divisjon" }],
  },
  {
    name: "Borg",
    venue: "Borg 2 KG",
    location: "Skien",
    lat: 59.16788,
    lng: 9.66011,
    teams: [{ name: "Borg", division: "6. divisjon" }],
  },
  {
    name: "Sundjordet",
    venue: "Frednes Hovedbane KG",
    location: "Porsgrunn",
    lat: 59.13427,
    lng: 9.64132,
    teams: [
      { name: "Sundjordet", division: "6. divisjon" },
      { name: "Sundjordet 2", division: "7. divisjon" },
    ],
  },
  {
    name: "Heddal",
    venue: "Bama kunstgressbane",
    location: "Heddal",
    lat: 59.59144,
    lng: 9.15361,
    teams: [
      { name: "Heddal", division: "6. divisjon" },
      { name: "Gransherad/Heddal 2", division: "7. divisjon" },
    ],
  },
  {
    name: "Drangedal",
    venue: "Drangedal Stadion KG",
    location: "Drangedal",
    lat: 59.09389,
    lng: 9.05064,
    teams: [
      { name: "Drangedal", division: "6. divisjon" },
      { name: "Drangedal 2", division: "7. divisjon" },
    ],
  },
  {
    name: "Nome",
    venue: "Lunde Hovedbane (Kåsa)",
    location: "Lunde",
    lat: 59.29899,
    lng: 9.09587,
    teams: [
      { name: "Nome", division: "6. divisjon" },
      { name: "Nome 2", division: "7. divisjon" },
    ],
  },
  {
    name: "Sauherad",
    venue: "Kjapp Hovedbane",
    location: "Sauherad",
    lat: 59.42137,
    lng: 9.32548,
    teams: [
      { name: "Sauherad", division: "6. divisjon" },
      { name: "Sauherad kvinner", division: "4. div kvinner" },
    ],
  },
  {
    name: "Siljan",
    venue: "Siljan Idrettspark KG",
    location: "Siljan",
    lat: 59.27226,
    lng: 9.70745,
    teams: [{ name: "Siljan", division: "6. divisjon" }],
  },
  {
    name: "Seljord",
    venue: "Eventyrøy Stadion KG",
    location: "Seljord",
    lat: 59.48755,
    lng: 8.64091,
    teams: [{ name: "Seljord", division: "6. divisjon" }],
  },
  {
    name: "Bamble",
    venue: "Rugtvedt KG",
    location: "Bamble",
    lat: 59.03981,
    lng: 9.67041,
    teams: [
      { name: "Bamble", division: "6. divisjon" },
      { name: "Bamble 2", division: "7. divisjon" },
    ],
  },
  {
    name: "Herøya",
    venue: "Herøya Hovedbane",
    location: "Herøya",
    lat: 59.11503,
    lng: 9.64717,
    teams: [{ name: "Herøya", division: "6. divisjon" }],
  },
  {
    name: "Gjerpen",
    venue: "Gjerpen Stadion KG",
    location: "Skien",
    lat: 59.22633,
    lng: 9.60513,
    teams: [{ name: "Gjerpen", division: "6. divisjon" }],
  },
  {
    name: "Skotfoss",
    venue: "Skotfoss Stadion KG",
    location: "Skotfoss",
    lat: 59.21042,
    lng: 9.53375,
    teams: [{ name: "Skotfoss", division: "7. divisjon" }],
  },
  {
    name: "Åfoss",
    venue: "Åfoss KG",
    location: "Ulefoss",
    lat: 59.19656,
    lng: 9.54288,
    teams: [{ name: "Åfoss", division: "7. divisjon" }],
  },
  {
    name: "Stridsklev",
    venue: "Stridsklev KG",
    location: "Porsgrunn",
    lat: 59.11288,
    lng: 9.66952,
    teams: [{ name: "Stridsklev", division: "7. divisjon" }],
  },
  {
    name: "Helle",
    venue: "Hellebanen KG",
    location: "Helle",
    lat: 58.90321,
    lng: 9.37090,
    teams: [{ name: "Helle", division: "7. divisjon" }],
  },
  {
    name: "Vinje",
    venue: "Åmot Stadion KG",
    location: "Vinje",
    lat: 59.57086,
    lng: 7.98863,
    teams: [{ name: "Vinje", division: "7. divisjon" }],
  },
  {
    name: "Tørn",
    venue: "Bø Stadion Tørdal",
    location: "Tørdal",
    lat: 59.15308,
    lng: 8.81356,
    teams: [{ name: "Tørn", division: "7. divisjon" }],
  },
  {
    name: "Pors",
    venue: "Pors 2 KG",
    location: "Porsgrunn",
    lat: 59.15134,
    lng: 9.64253,
    teams: [{ name: "Pors 3", division: "7. divisjon" }],
  },
];
