export interface ClubTeam {
  name: string;
  division: string;
}

export interface Club {
  slug: string;
  name: string;
  logo: string;
  venue: string;
  location: string;
  lat: number;
  lng: number;
  teams: ClubTeam[];
}

export const clubs: Club[] = [
  {
    slug: "hei",
    name: "Hei",
    logo: "https://images.fotball.no/clublogos/537.png",
    venue: "Mortens Plass KG",
    location: "Skien",
    lat: 59.08838, lng: 9.68080,
    teams: [
      { name: "Hei", division: "4. divisjon" },
      { name: "Hei 2", division: "5. divisjon" },
      { name: "Hei 3", division: "7. divisjon" },
    ],
  },
  {
    slug: "langangen",
    name: "Langangen",
    logo: "https://images.fotball.no/clublogos/539.png",
    venue: "Myrhaug stadion",
    location: "Langangen",
    lat: 59.08267, lng: 9.80952,
    teams: [{ name: "Langangen", division: "4. divisjon" }],
  },
  {
    slug: "eidanger",
    name: "Eidanger",
    logo: "https://images.fotball.no/clublogos/536.png",
    venue: "Eidangerbanen KG",
    location: "Eidanger",
    lat: 59.11544, lng: 9.69604,
    teams: [
      { name: "Eidanger", division: "4. divisjon" },
      { name: "Eidanger 2", division: "5. divisjon" },
    ],
  },
  {
    slug: "odd",
    name: "Odd",
    logo: "https://images.fotball.no/clublogos/556.png",
    venue: "Skagerak Arena",
    location: "Skien",
    lat: 59.21151, lng: 9.58986,
    teams: [
      { name: "Odd 3", division: "4. divisjon" },
      { name: "Odd 2 kvinner", division: "4. div kvinner" },
    ],
  },
  {
    slug: "uraedd",
    name: "Urædd",
    logo: "https://images.fotball.no/clublogos/542.png",
    venue: "Urædd KG / Kjølnes",
    location: "Porsgrunn",
    lat: 59.14167, lng: 9.66643,
    teams: [
      { name: "Urædd", division: "4. divisjon" },
      { name: "Urædd 2", division: "5. divisjon" },
      { name: "Urædd 3", division: "7. divisjon" },
      { name: "Urædd kvinner", division: "4. div kvinner" },
    ],
  },
  {
    slug: "storm",
    name: "Storm",
    logo: "https://images.fotball.no/clublogos/552.png",
    venue: "Bratsberg KG",
    location: "Bratsberg",
    lat: 59.20429, lng: 9.62406,
    teams: [
      { name: "Storm", division: "4. divisjon" },
      { name: "Storm 2", division: "5. divisjon" },
      { name: "Storm 3", division: "7. divisjon" },
      { name: "Fossum/Storm kvinner", division: "4. div kvinner" },
    ],
  },
  {
    slug: "tollnes",
    name: "Tollnes",
    logo: "https://images.fotball.no/clublogos/553.png",
    venue: "Tollnes Stadion KG",
    location: "Skien",
    lat: 59.16105, lng: 9.62841,
    teams: [
      { name: "Tollnes", division: "4. divisjon" },
      { name: "Tollnes kvinner", division: "4. div kvinner" },
    ],
  },
  {
    slug: "notodden",
    name: "Notodden FK",
    logo: "https://images.fotball.no/clublogos/1687.png",
    venue: "Idrettsparken KG",
    location: "Notodden",
    lat: 59.56364, lng: 9.25984,
    teams: [
      { name: "Notodden 2", division: "4. divisjon" },
    ],
  },
  {
    slug: "brevik",
    name: "Brevik",
    logo: "https://images.fotball.no/clublogos/535.png",
    venue: "Furulund KG",
    location: "Brevik",
    lat: 59.05617, lng: 9.69432,
    teams: [
      { name: "Brevik", division: "4. divisjon" },
      { name: "Brevik 2", division: "6. divisjon" },
    ],
  },
  {
    slug: "gulset",
    name: "Gulset",
    logo: "https://images.fotball.no/clublogos/546.png",
    venue: "Gulset KG",
    location: "Skien",
    lat: 59.21169, lng: 9.55546,
    teams: [
      { name: "Gulset", division: "4. divisjon" },
      { name: "Gulset 2", division: "7. divisjon" },
    ],
  },
  {
    slug: "skarphedin",
    name: "Skarphedin",
    logo: "https://images.fotball.no/clublogos/578.png",
    venue: "Sandvoll / Telemarkshallen KG",
    location: "Bø i Telemark",
    lat: 59.41802, lng: 9.07809,
    teams: [
      { name: "Skarphedin", division: "4. divisjon" },
      { name: "Skarphedin 2", division: "7. divisjon" },
      { name: "Skarphedin kvinner", division: "4. div kvinner" },
    ],
  },
  {
    slug: "stathelle-langesund",
    name: "Stathelle/Langesund",
    logo: "https://images.fotball.no/clublogos/566.png",
    venue: "Bunes KG",
    location: "Stathelle",
    lat: 59.03696, lng: 9.70568,
    teams: [{ name: "Stathelle/Langesund", division: "4. divisjon" }],
  },
  {
    slug: "snogg",
    name: "Snøgg",
    logo: "https://images.fotball.no/clublogos/561.png",
    venue: "Notodden KG",
    location: "Notodden",
    lat: 59.57093, lng: 9.27054,
    teams: [
      { name: "Snøgg", division: "5. divisjon" },
      { name: "Snøgg kvinner", division: "4. div kvinner" },
    ],
  },
  {
    slug: "sannidal",
    name: "Sannidal",
    logo: "https://images.fotball.no/clublogos/570.png",
    venue: "Kolbånn KG",
    location: "Sannidal",
    lat: 58.90143, lng: 9.31200,
    teams: [
      { name: "Sannidal", division: "5. divisjon" },
      { name: "Sannidal 2", division: "7. divisjon" },
    ],
  },
  {
    slug: "skidar",
    name: "Skidar",
    logo: "https://images.fotball.no/clublogos/549.png",
    venue: "Helges Plass KG",
    location: "Skien",
    lat: 59.19427, lng: 9.62885,
    teams: [{ name: "Skidar", division: "5. divisjon" }],
  },
  {
    slug: "skiens-grane",
    name: "Skiens Grane",
    logo: "https://images.fotball.no/clublogos/550.png",
    venue: "Granebanen KG",
    location: "Skien",
    lat: 59.20065, lng: 9.59477,
    teams: [{ name: "Skiens Grane", division: "5. divisjon" }],
  },
  {
    slug: "herkules",
    name: "Herkules",
    logo: "https://images.fotball.no/clublogos/557.png",
    venue: "Herkules KG",
    location: "Skien",
    lat: 59.18246, lng: 9.59941,
    teams: [
      { name: "Herkules", division: "5. divisjon" },
      { name: "Herkules kvinner", division: "4. div kvinner" },
    ],
  },
  {
    slug: "langesund-stathelle",
    name: "Langesund/Stathelle",
    logo: "https://images.fotball.no/clublogos/565.png",
    venue: "Slåttenes KG",
    location: "Langesund",
    lat: 59.00000, lng: 9.74279,
    teams: [{ name: "Langesund/Stathelle", division: "5. divisjon" }],
  },
  {
    slug: "kroken",
    name: "Kroken",
    logo: "https://images.fotball.no/clublogos/573.png",
    venue: "Sandvann stadion",
    location: "Neslandsvatn",
    lat: 58.93230, lng: 9.12725,
    teams: [{ name: "Kroken", division: "5. divisjon" }],
  },
  {
    slug: "kragero",
    name: "Kragerø",
    logo: "https://images.fotball.no/clublogos/1626.png",
    venue: "Kragerø Stadion KG",
    location: "Kragerø",
    lat: 58.87111, lng: 9.40673,
    teams: [{ name: "Kragerø", division: "5. divisjon" }],
  },
  {
    slug: "borg",
    name: "Borg",
    logo: "https://images.fotball.no/clublogos/543.png",
    venue: "Borg 2 KG",
    location: "Skien",
    lat: 59.16788, lng: 9.66011,
    teams: [{ name: "Borg", division: "6. divisjon" }],
  },
  {
    slug: "sundjordet",
    name: "Sundjordet",
    logo: "https://images.fotball.no/clublogos/541.png",
    venue: "Frednes Hovedbane KG",
    location: "Porsgrunn",
    lat: 59.13427, lng: 9.64132,
    teams: [
      { name: "Sundjordet", division: "6. divisjon" },
      { name: "Sundjordet 2", division: "7. divisjon" },
    ],
  },
  {
    slug: "heddal",
    name: "Heddal",
    logo: "https://images.fotball.no/clublogos/559.png",
    venue: "Bama kunstgressbane",
    location: "Heddal",
    lat: 59.59144, lng: 9.15361,
    teams: [
      { name: "Heddal", division: "6. divisjon" },
    ],
  },
  {
    slug: "gransherad",
    name: "Gransherad/Heddal 2",
    logo: "https://images.fotball.no/clublogos/558.png",
    venue: "Lerkelunden Fotballbane",
    location: "Gransherad",
    lat: 59.69276, lng: 9.02849,
    teams: [
      { name: "Gransherad/Heddal 2", division: "7. divisjon" },
    ],
  },
  {
    slug: "drangedal",
    name: "Drangedal",
    logo: "https://images.fotball.no/clublogos/571.png",
    venue: "Drangedal Stadion KG",
    location: "Drangedal",
    lat: 59.09389, lng: 9.05064,
    teams: [
      { name: "Drangedal", division: "6. divisjon" },
      { name: "Drangedal 2", division: "7. divisjon" },
    ],
  },
  {
    slug: "nome",
    name: "Nome",
    logo: "https://images.fotball.no/clublogos/3274.png",
    venue: "Lunde Hovedbane (Kåsa)",
    location: "Lunde",
    lat: 59.29899, lng: 9.09587,
    teams: [
      { name: "Nome", division: "6. divisjon" },
      { name: "Nome 2", division: "7. divisjon" },
    ],
  },
  {
    slug: "sauherad",
    name: "Sauherad",
    logo: "https://images.fotball.no/clublogos/579.png",
    venue: "Kjapp Hovedbane",
    location: "Sauherad",
    lat: 59.42137, lng: 9.32548,
    teams: [
      { name: "Sauherad", division: "6. divisjon" },
      { name: "Sauherad kvinner", division: "4. div kvinner" },
    ],
  },
  {
    slug: "siljan",
    name: "Siljan",
    logo: "https://images.fotball.no/clublogos/562.png",
    venue: "Siljan Idrettspark KG",
    location: "Siljan",
    lat: 59.27226, lng: 9.70745,
    teams: [{ name: "Siljan", division: "6. divisjon" }],
  },
  {
    slug: "seljord",
    name: "Seljord",
    logo: "https://images.fotball.no/clublogos/590.png",
    venue: "Eventyrøy Stadion KG",
    location: "Seljord",
    lat: 59.48755, lng: 8.64091,
    teams: [{ name: "Seljord", division: "6. divisjon" }],
  },
  {
    slug: "bamble",
    name: "Bamble",
    logo: "https://images.fotball.no/clublogos/563.png",
    venue: "Rugtvedt KG",
    location: "Bamble",
    lat: 59.03981, lng: 9.67041,
    teams: [
      { name: "Bamble", division: "6. divisjon" },
      { name: "Bamble 2", division: "7. divisjon" },
    ],
  },
  {
    slug: "heroya",
    name: "Herøya",
    logo: "https://images.fotball.no/clublogos/538.png",
    venue: "Herøya Hovedbane",
    location: "Herøya",
    lat: 59.11503, lng: 9.64717,
    teams: [{ name: "Herøya", division: "6. divisjon" }],
  },
  {
    slug: "gjerpen",
    name: "Gjerpen",
    logo: "https://images.fotball.no/clublogos/545.png",
    venue: "Gjerpen Stadion KG",
    location: "Skien",
    lat: 59.22633, lng: 9.60513,
    teams: [{ name: "Gjerpen", division: "6. divisjon" }],
  },
  {
    slug: "skotfoss",
    name: "Skotfoss",
    logo: "https://images.fotball.no/clublogos/551.png",
    venue: "Skotfoss Stadion KG",
    location: "Skotfoss",
    lat: 59.21042, lng: 9.53375,
    teams: [{ name: "Skotfoss", division: "7. divisjon" }],
  },
  {
    slug: "afoss",
    name: "Åfoss",
    logo: "https://images.fotball.no/clublogos/554.png",
    venue: "Åfoss KG",
    location: "Ulefoss",
    lat: 59.19656, lng: 9.54288,
    teams: [{ name: "Åfoss", division: "7. divisjon" }],
  },
  {
    slug: "stridsklev",
    name: "Stridsklev",
    logo: "https://images.fotball.no/clublogos/540.png",
    venue: "Stridsklev KG",
    location: "Porsgrunn",
    lat: 59.11288, lng: 9.66952,
    teams: [{ name: "Stridsklev", division: "7. divisjon" }],
  },
  {
    slug: "helle",
    name: "Helle",
    logo: "https://images.fotball.no/clublogos/568.png",
    venue: "Hellebanen KG",
    location: "Helle",
    lat: 58.90321, lng: 9.37090,
    teams: [{ name: "Helle", division: "7. divisjon" }],
  },
  {
    slug: "vinje",
    name: "Vinje",
    logo: "https://images.fotball.no/clublogos/600.png",
    venue: "Åmot Stadion KG",
    location: "Vinje",
    lat: 59.57086, lng: 7.98863,
    teams: [{ name: "Vinje", division: "7. divisjon" }],
  },
  {
    slug: "torn",
    name: "Tørn",
    logo: "https://images.fotball.no/clublogos/574.png",
    venue: "Bø Stadion Tørdal",
    location: "Tørdal",
    lat: 59.15308, lng: 8.81356,
    teams: [{ name: "Tørn", division: "7. divisjon" }],
  },
  {
    slug: "pors",
    name: "Pors",
    logo: "https://images.fotball.no/clublogos/1819.png",
    venue: "Pors 2 KG",
    location: "Porsgrunn",
    lat: 59.15134, lng: 9.64253,
    teams: [{ name: "Pors 3", division: "7. divisjon" }],
  },
];
