export interface Player {
  name: string;
  number: number | null;
  position: "Keeper" | "Forsvar" | "Midtbane" | "Angrep" | "Ukjent";
}

export interface TeamSquad {
  clubSlug: string;
  teamName: string;
  division: string;
  players: Player[];
}

export const squads: TeamSquad[] = [
  // 4. DIVISJON
  {
    clubSlug: "eidanger",
    teamName: "Eidanger",
    division: "4. divisjon",
    players: [
      { name: "Marcus Ferdinand Auraaen Lindberg", number: 12, position: "Keeper" },
      { name: "Simen Thon", number: 2, position: "Forsvar" },
      { name: "Kristián Gallik", number: 4, position: "Forsvar" },
      { name: "Maximilian Kreutzer", number: 6, position: "Forsvar" },
      { name: "Marius Kolve Johnsen", number: 23, position: "Forsvar" },
      { name: "Daniel Kristoffer Breiland Teigen", number: 21, position: "Midtbane" },
      { name: "Simon Disch Lindvig", number: 22, position: "Midtbane" },
      { name: "Samuel Hoff Fosse", number: 25, position: "Midtbane" },
      { name: "Håvard Mæland Ramslien", number: 26, position: "Midtbane" },
      { name: "Marcus Engh-Ajer", number: 37, position: "Midtbane" },
      { name: "Daniel Ismail Bortne", number: 77, position: "Midtbane" },
      { name: "Oliver Walsøe Strøm", number: 7, position: "Angrep" },
      { name: "Filip Larsen Gripsgård", number: 8, position: "Angrep" },
      { name: "Haakon Aaltvedt Pettersen", number: 10, position: "Angrep" },
      { name: "Martin Søvik Røren", number: 17, position: "Angrep" },
      { name: "Marius Lundeberg Enger", number: 30, position: "Angrep" },
      { name: "Robin Kongsro", number: null, position: "Ukjent" },
      { name: "Ole Myklebust Engh", number: null, position: "Ukjent" },
      { name: "Joakim Holmen Jahnsen", number: null, position: "Ukjent" },
      { name: "Pål Røsvik", number: null, position: "Ukjent" },
      { name: "Gulled Mahamed Omar", number: null, position: "Ukjent" },
      { name: "Edi Coli", number: null, position: "Ukjent" },
      { name: "Bent Linus Bertelsen", number: null, position: "Ukjent" },
      { name: "Hasan Mahamed Omar", number: 28, position: "Ukjent" },
      { name: "Bent Mathias Hoff Fosse", number: 29, position: "Ukjent" },
      { name: "Kristoffer Nygård", number: 39, position: "Ukjent" },
    ],
  },
  {
    clubSlug: "hei",
    teamName: "Hei",
    division: "4. divisjon",
    players: [
      { name: "Lasse Tørnes Olsen", number: 2, position: "Forsvar" },
      { name: "Ole Martin Karlsen Sagarino", number: 10, position: "Midtbane" },
      { name: "Daniel André Wingereid Lauritzen", number: 7, position: "Angrep" },
      { name: "Patrick Løvig", number: 11, position: "Angrep" },
      { name: "Andre Gregersen", number: 17, position: "Angrep" },
      { name: "Nicolay Henriksen Hagen", number: 5, position: "Ukjent" },
      { name: "Jon Anil Solvik Prabhakar", number: 8, position: "Ukjent" },
      { name: "Alexander Lundberg", number: 22, position: "Ukjent" },
      { name: "Bendik Ripegutu Nygård", number: 24, position: "Ukjent" },
      { name: "Daniel Amankona Koranteng", number: 27, position: "Ukjent" },
      { name: "Andreas Ytredal", number: 29, position: "Ukjent" },
    ],
  },
  {
    clubSlug: "uraedd",
    teamName: "Urædd",
    division: "4. divisjon",
    players: [
      { name: "Marcus Furevik Utne", number: 1, position: "Keeper" },
      { name: "Theodor Kronstad Johansen", number: 13, position: "Keeper" },
      { name: "Mathias Haugen", number: 26, position: "Keeper" },
      { name: "Ola Dalene", number: null, position: "Forsvar" },
      { name: "Federico Tisera Johansen", number: 2, position: "Forsvar" },
      { name: "Leander Meen-Dahlen", number: 3, position: "Forsvar" },
      { name: "Torkil Amlie Amundsen", number: 4, position: "Forsvar" },
      { name: "Nemanja Mladenovic", number: 5, position: "Forsvar" },
      { name: "Kristoffer Skoglund Kristiansen", number: 14, position: "Forsvar" },
      { name: "Wahab Fagari", number: 19, position: "Forsvar" },
      { name: "Kristian Berg", number: 22, position: "Forsvar" },
      { name: "Philip Furevik Utne", number: 23, position: "Forsvar" },
      { name: "Andreas Beyer Flohr", number: 27, position: "Forsvar" },
      { name: "Anthony Occean", number: 44, position: "Forsvar" },
      { name: "Kristoffer Berg Høegh-Larsen", number: 6, position: "Midtbane" },
      { name: "Prince Allan Mlagulwa", number: 7, position: "Midtbane" },
      { name: "Elod Coli", number: 8, position: "Midtbane" },
      { name: "Mokhmad Sjamsudijevitsj Ibragimov", number: 10, position: "Midtbane" },
      { name: "Jørgen Aslaksen", number: 17, position: "Midtbane" },
      { name: "Magnus Hagen Noste", number: 20, position: "Midtbane" },
      { name: "Mikkel Kiste-Johnsen", number: 21, position: "Midtbane" },
      { name: "Jesper Skoglund Kristiansen", number: 41, position: "Midtbane" },
      { name: "Teodor Numme", number: 77, position: "Midtbane" },
      { name: "Granit Shala", number: 9, position: "Angrep" },
      { name: "Momodou Lamin Touray", number: 15, position: "Angrep" },
      { name: "Emanuel Valle", number: 24, position: "Angrep" },
    ],
  },
  {
    clubSlug: "odd",
    teamName: "Odd 3",
    division: "4. divisjon",
    players: [
      { name: "Sebastian Hansen", number: 1, position: "Keeper" },
      { name: "Idar Nordby Lysgård", number: 12, position: "Keeper" },
      { name: "Storm Leander Øines", number: 24, position: "Keeper" },
      { name: "Jacob Buus Jacobsen", number: 2, position: "Forsvar" },
      { name: "Nikolas Walstad", number: 4, position: "Forsvar" },
      { name: "Hans Christian Bonnesen", number: 5, position: "Forsvar" },
      { name: "Jakob Vadstrup Larsen", number: 6, position: "Forsvar" },
      { name: "Samuel Skree Skjeldal", number: 13, position: "Forsvar" },
      { name: "Julian Lerato Gunnerød", number: 14, position: "Forsvar" },
      { name: "Oliver Svenungsen Skau", number: 15, position: "Forsvar" },
      { name: "Godwill Fabio Ambrose", number: 17, position: "Forsvar" },
      { name: "Jonathan Roaas Engen", number: 29, position: "Forsvar" },
      { name: "Filip Rønningen Jørgensen", number: 7, position: "Midtbane" },
      { name: "Per Daniel Söderberg", number: 8, position: "Midtbane" },
      { name: "Mukhtar Mustapha Adamu", number: 16, position: "Midtbane" },
      { name: "Syver Aas", number: 18, position: "Midtbane" },
      { name: "Noah Kojo Akogyeram-Fjeldberg", number: 23, position: "Midtbane" },
      { name: "Kristian Rodgers Holte", number: 27, position: "Midtbane" },
      { name: "Isak Bae Eikeland", number: 31, position: "Midtbane" },
      { name: "Oscar Yohannes Essayas", number: 34, position: "Midtbane" },
      { name: "Sanel Bojadzic", number: 9, position: "Angrep" },
      { name: "Villads Appel Rasmussen", number: 10, position: "Angrep" },
      { name: "Casper Glenna Andersen", number: 11, position: "Angrep" },
      { name: "Abduljeleel Toluwalashe Abdulateef", number: 19, position: "Angrep" },
      { name: "Hinrik Hardarson", number: 20, position: "Angrep" },
      { name: "Faniel Temesgen Tewelde", number: 28, position: "Angrep" },
      { name: "Gabriel Occean", number: 30, position: "Angrep" },
      { name: "Elion Krosa", number: 32, position: "Angrep" },
      { name: "Lucas Kifle Adresom", number: 33, position: "Angrep" },
    ],
  },
  {
    clubSlug: "storm",
    teamName: "Storm",
    division: "4. divisjon",
    players: [
      { name: "Atle Brattum", number: 2, position: "Forsvar" },
      { name: "Oliver Thorstein Lønberg", number: null, position: "Midtbane" },
      { name: "Sander Grønhaug-Weber", number: 26, position: "Midtbane" },
      { name: "Marco Lindalen Da Silva", number: 5, position: "Angrep" },
      { name: "Peder Bang Synnes", number: 15, position: "Angrep" },
      { name: "Erik Sergio Skogen", number: 90, position: "Angrep" },
      { name: "Mathias Weholt Hansen", number: null, position: "Ukjent" },
      { name: "Tarjei Solvang-Lothe", number: null, position: "Ukjent" },
      { name: "Markus Andre Hauen", number: null, position: "Ukjent" },
      { name: "Eirik Torblå", number: null, position: "Ukjent" },
      { name: "Tobias Torblå", number: null, position: "Ukjent" },
      { name: "Magnus Nordengen", number: null, position: "Ukjent" },
      { name: "Fernando Mzambi", number: null, position: "Ukjent" },
      { name: "Sebastian Sandøy Sneltvedt", number: 9, position: "Ukjent" },
    ],
  },
  {
    clubSlug: "tollnes",
    teamName: "Tollnes",
    division: "4. divisjon",
    players: [
      { name: "Délégue Zigashane Lukungu", number: null, position: "Ukjent" },
      { name: "Mathias Aandal Pedersen", number: null, position: "Ukjent" },
      { name: "Ali Al-Askari", number: null, position: "Ukjent" },
      { name: "Qendrim Alija", number: null, position: "Ukjent" },
      { name: "Nicolai Meland Handeland", number: null, position: "Ukjent" },
      { name: "Marcus Holthe Kvam", number: null, position: "Ukjent" },
      { name: "Simon Grotnes", number: null, position: "Ukjent" },
      { name: "Jonas Lange Gyberg", number: null, position: "Ukjent" },
      { name: "Sebastian Botea", number: null, position: "Ukjent" },
      { name: "Noa Westeren Lakselvnes", number: null, position: "Ukjent" },
      { name: "Marius Aandal Pedersen", number: null, position: "Ukjent" },
      { name: "Jon-André Moen Enggravslia", number: 5, position: "Ukjent" },
    ],
  },
  {
    clubSlug: "notodden",
    teamName: "Notodden 2",
    division: "4. divisjon",
    players: [
      { name: "Mahmud Mustafa Ahmed", number: null, position: "Ukjent" },
      { name: "Mathias Slåtta Folserås", number: null, position: "Ukjent" },
      { name: "Olav Bakka Tvervik", number: null, position: "Ukjent" },
      { name: "Martin Thorsberg Dahl", number: null, position: "Ukjent" },
      { name: "Jan Olav Weiseth Bakken", number: null, position: "Ukjent" },
      { name: "Sigurd Råsberg", number: 8, position: "Ukjent" },
      { name: "Hans Torjus Stykket Gampedalen", number: 10, position: "Ukjent" },
      { name: "Jan Bergesen", number: 12, position: "Ukjent" },
      { name: "Christian Barth-Rauland", number: 16, position: "Ukjent" },
      { name: "Sondre Svarstad", number: 19, position: "Ukjent" },
      { name: "Tor André Nordbø", number: 22, position: "Ukjent" },
      { name: "Bjørnar Tobiassen", number: 26, position: "Ukjent" },
      { name: "Sondre Johan Straand", number: 31, position: "Ukjent" },
    ],
  },
  {
    clubSlug: "brevik",
    teamName: "Brevik",
    division: "4. divisjon",
    players: [
      { name: "Hans Simen Hansen", number: 1, position: "Keeper" },
      { name: "Sigurd Berge Hansen", number: 12, position: "Keeper" },
      { name: "Ulrik Eriksen", number: null, position: "Forsvar" },
      { name: "Jesper Aaby Bergkåsa", number: 2, position: "Forsvar" },
      { name: "Morten Erling Kvam", number: 8, position: "Forsvar" },
      { name: "Truls Klewe Arnesen", number: 15, position: "Forsvar" },
      { name: "Herman Berge Hansen", number: 23, position: "Forsvar" },
      { name: "Christian Kjærnes", number: 24, position: "Forsvar" },
      { name: "Kasper Onsrud Ingebretsen", number: 30, position: "Forsvar" },
      { name: "Simen Edvardsen", number: 4, position: "Midtbane" },
      { name: "Maxim Romfog Ingvaldsen", number: 14, position: "Midtbane" },
      { name: "Mathias Bråthen", number: 18, position: "Midtbane" },
      { name: "Thor Henrik Skauen", number: 27, position: "Midtbane" },
      { name: "Markus Vonstett", number: 36, position: "Midtbane" },
      { name: "Brede Storhaug Lien", number: 10, position: "Angrep" },
      { name: "Johan Camilo Finborud Bamle", number: 13, position: "Angrep" },
      { name: "Matias Herum Roligheten", number: 19, position: "Angrep" },
      { name: "Johannes Flaatten", number: 43, position: "Angrep" },
      { name: "Erlend Falch Lindberg", number: null, position: "Ukjent" },
      { name: "Bastian Eilefstjønn-Solli", number: null, position: "Ukjent" },
    ],
  },
  {
    clubSlug: "gulset",
    teamName: "Gulset",
    division: "4. divisjon",
    players: [
      { name: "Nikolai Berg Fjeldavlie", number: 1, position: "Keeper" },
      { name: "William Lloyd", number: 4, position: "Forsvar" },
      { name: "Even Honningdal Nilsen", number: 5, position: "Forsvar" },
      { name: "Vegard Birkeland", number: 17, position: "Forsvar" },
      { name: "Ole-Andreas Arnulf", number: 24, position: "Forsvar" },
      { name: "Noah Riesner-Fredriksen", number: 6, position: "Midtbane" },
      { name: "Joakim Kleven", number: 27, position: "Midtbane" },
      { name: "Jøran Vadder Hansen", number: 22, position: "Angrep" },
      { name: "Isak Hassan", number: 28, position: "Angrep" },
    ],
  },
  {
    clubSlug: "skarphedin",
    teamName: "Skarphedin",
    division: "4. divisjon",
    players: [
      { name: "Olav Hagen", number: 1, position: "Keeper" },
      { name: "Even Sauar Wad", number: 12, position: "Keeper" },
      { name: "Ahmed Abdulrahman Mohamed", number: 14, position: "Forsvar" },
      { name: "Sjur Holte", number: 23, position: "Forsvar" },
      { name: "Bernt Skipstad Ollestad", number: 6, position: "Midtbane" },
      { name: "Ingvald Godal Eidissen", number: 5, position: "Angrep" },
      { name: "Joel Samiel Ghetachew", number: 7, position: "Angrep" },
      { name: "Jone Evensen Edingsås", number: 18, position: "Angrep" },
      { name: "Johannes Pailow", number: 20, position: "Ukjent" },
      { name: "Torjus Tvedt-Våer", number: 22, position: "Ukjent" },
    ],
  },
  // 5. DIVISJON
  {
    clubSlug: "snogg",
    teamName: "Snøgg",
    division: "5. divisjon",
    players: [
      { name: "Markus Tveiten Natadal", number: null, position: "Forsvar" },
      { name: "Lars Haugan", number: 2, position: "Forsvar" },
      { name: "Lasse Røed", number: 14, position: "Forsvar" },
      { name: "Mathias Kjosvold Pedersen", number: 3, position: "Midtbane" },
      { name: "Tarjei Eliassen Urdal", number: 13, position: "Midtbane" },
      { name: "Tor-Mattis Ebbesvik Kåven", number: 21, position: "Midtbane" },
      { name: "Daniel Jonas Beer Grooten", number: null, position: "Angrep" },
      { name: "Stian Kvernstuen Grimsrud", number: 9, position: "Angrep" },
      { name: "Vetle Kirkemoen Slette", number: null, position: "Ukjent" },
      { name: "Olav Lurås Yli", number: 4, position: "Ukjent" },
      { name: "Erlend Kasin Østern", number: 8, position: "Ukjent" },
      { name: "Viktor Adam Storhaug Amari", number: 10, position: "Ukjent" },
      { name: "Eirik Haugen Haslekås", number: 11, position: "Ukjent" },
      { name: "Halvor Lien Haug", number: 17, position: "Ukjent" },
    ],
  },
  {
    clubSlug: "skidar",
    teamName: "Skidar",
    division: "5. divisjon",
    players: [
      { name: "Even Harjo Bakke", number: null, position: "Keeper" },
      { name: "Fredrik Wærstad Sølland", number: 69, position: "Keeper" },
      { name: "Thomas Mørkesdal Claussen", number: 4, position: "Forsvar" },
      { name: "Elias Reinholt Juve-Andresen", number: 9, position: "Forsvar" },
      { name: "Isak Bjaarstad Aspheim", number: 16, position: "Forsvar" },
      { name: "Marius Jensen Sneltvedt", number: 18, position: "Forsvar" },
      { name: "Sander Høgli Johnsen", number: null, position: "Midtbane" },
      { name: "Simen Theie Havenstrøm", number: 5, position: "Midtbane" },
      { name: "Aleksander Bernhard Toreskaas Skau", number: 8, position: "Midtbane" },
      { name: "Stian Drageset Thomsen", number: 14, position: "Midtbane" },
      { name: "Christian Tollefsen", number: 77, position: "Midtbane" },
      { name: "Truls Realfsen", number: 10, position: "Angrep" },
      { name: "Kevin Dusmanu", number: 15, position: "Angrep" },
      { name: "Boye Bomhoff", number: 23, position: "Angrep" },
      { name: "Jon Helge Vigeland", number: 29, position: "Angrep" },
    ],
  },
  {
    clubSlug: "skiens-grane",
    teamName: "Skiens Grane",
    division: "5. divisjon",
    players: [
      { name: "Brian Kadir Sener", number: 1, position: "Keeper" },
      { name: "Birk Hansen Stokke", number: 41, position: "Keeper" },
      { name: "Abdirahman Mohammed", number: 6, position: "Forsvar" },
      { name: "Haakon Høimyhr Skaate", number: 19, position: "Forsvar" },
      { name: "Ole-Kristian Wighus Nordby", number: 28, position: "Forsvar" },
      { name: "Sarmen Hakobkjochwsan", number: 10, position: "Midtbane" },
      { name: "Elias Tsatsouras Kaalstad", number: 14, position: "Midtbane" },
      { name: "Bodery Ismail", number: 24, position: "Midtbane" },
      { name: "Leonard Gashi", number: 7, position: "Angrep" },
      { name: "Fredrik Wines Østby", number: 11, position: "Angrep" },
      { name: "Hanad Abdulkadir Jama", number: 15, position: "Angrep" },
      { name: "Sylejmon Vokshi", number: 22, position: "Angrep" },
      { name: "Åsmund Gulseth Berg", number: 99, position: "Angrep" },
    ],
  },
  {
    clubSlug: "herkules",
    teamName: "Herkules",
    division: "5. divisjon",
    players: [
      { name: "Noah Tangedal Elvenes", number: null, position: "Keeper" },
      { name: "Cornelius Vinnstad Heibø", number: 1, position: "Keeper" },
      { name: "Brian Haukås Hoem", number: 2, position: "Forsvar" },
      { name: "Gunnar Sønstebø Svendseid", number: 5, position: "Forsvar" },
      { name: "Eirik Skaug Andersen", number: 18, position: "Forsvar" },
      { name: "Kristian Lund Ramstad", number: 19, position: "Forsvar" },
      { name: "Magnus Rognlien", number: 21, position: "Forsvar" },
      { name: "Sander Lussand Herum", number: 4, position: "Midtbane" },
      { name: "Teodor Sørensen Solvang", number: 8, position: "Midtbane" },
      { name: "Leander André Lillefjære", number: 10, position: "Midtbane" },
      { name: "Tom Atle Storebø", number: 13, position: "Midtbane" },
      { name: "Lars Christian Hanssen", number: 9, position: "Angrep" },
      { name: "Håvard Erikstein Norendal", number: 17, position: "Angrep" },
      { name: "Fredrik Oldrup Hansen", number: 29, position: "Angrep" },
    ],
  },
  {
    clubSlug: "kroken",
    teamName: "Kroken",
    division: "5. divisjon",
    players: [
      { name: "Anders Haugen Rønning", number: 4, position: "Keeper" },
      { name: "Sindre Stenger Vala", number: 66, position: "Keeper" },
      { name: "Elias Bråtane Øygarden", number: 2, position: "Forsvar" },
      { name: "Simen Rosland", number: 5, position: "Forsvar" },
      { name: "Glenn Tommy Haugen", number: 8, position: "Forsvar" },
      { name: "Henrik Solli", number: 22, position: "Forsvar" },
      { name: "Joakim Solli", number: 45, position: "Forsvar" },
      { name: "Øyvind Skarelven", number: 14, position: "Midtbane" },
      { name: "Christian Bærstad", number: 16, position: "Midtbane" },
      { name: "Andreas Sundbø Jacobsen", number: 20, position: "Midtbane" },
      { name: "Sindre Bråten Skoglund", number: 23, position: "Midtbane" },
      { name: "Tomas Stenger Fostveit", number: 7, position: "Angrep" },
      { name: "Joachim Sandåker", number: 9, position: "Angrep" },
      { name: "Jon-Reidar Haugland", number: 10, position: "Angrep" },
      { name: "Thomas Kalmar Rønning", number: 15, position: "Angrep" },
      { name: "Markus Brødsjø", number: 17, position: "Angrep" },
    ],
  },
  {
    clubSlug: "kragero",
    teamName: "Kragerø",
    division: "5. divisjon",
    players: [
      { name: "Lars Magnus Sundbø Jacobsen", number: 1, position: "Keeper" },
      { name: "Janko Antic", number: 2, position: "Forsvar" },
      { name: "Anders Eikenes", number: 6, position: "Forsvar" },
      { name: "Marius Beck Wilhelmsen", number: 40, position: "Forsvar" },
      { name: "Wuttipong Wongprakhon", number: 55, position: "Midtbane" },
      { name: "Stian Emil Fjeld Gundersen", number: 10, position: "Angrep" },
      { name: "Thomas Fosso Kristiansen", number: null, position: "Forsvar" },
      { name: "Magnus Ødegaarden", number: null, position: "Forsvar" },
      { name: "Lars Sandvik Sulesund", number: null, position: "Forsvar" },
      { name: "Gunnar Wåsjø Simonsen", number: null, position: "Midtbane" },
      { name: "Runar Olsen Hustad", number: null, position: "Midtbane" },
      { name: "Steffen Monrad Thoresen", number: null, position: "Angrep" },
      { name: "Erik Norheim", number: null, position: "Angrep" },
    ],
  },
  // 6. DIVISJON
  {
    clubSlug: "borg",
    teamName: "Borg",
    division: "6. divisjon",
    players: [
      { name: "Stian Kåsene Vinnes", number: 1, position: "Keeper" },
      { name: "Kristian Mellesdal Bakken", number: 12, position: "Keeper" },
      { name: "Alexander Borlaug", number: 3, position: "Forsvar" },
      { name: "Sander Skotnes Stølan", number: 4, position: "Forsvar" },
      { name: "Lars Dalene", number: 6, position: "Forsvar" },
      { name: "Daniel Nicolai Olavson", number: 9, position: "Forsvar" },
      { name: "Magnus Svarstad", number: 11, position: "Forsvar" },
      { name: "Kim-André Espelid Jamtvedt", number: 5, position: "Midtbane" },
      { name: "Andreas Ringsevjen", number: 7, position: "Midtbane" },
      { name: "Erik Nakken Vinje", number: 13, position: "Midtbane" },
      { name: "Tony Dewey", number: 15, position: "Midtbane" },
      { name: "Even Berntsen Kåsa", number: 2, position: "Angrep" },
      { name: "Elias Haugerød Melaas", number: 8, position: "Angrep" },
      { name: "Gøran Kallåk", number: 10, position: "Angrep" },
      { name: "Thomas Hogstad", number: 16, position: "Angrep" },
    ],
  },
  {
    clubSlug: "drangedal",
    teamName: "Drangedal",
    division: "6. divisjon",
    players: [
      { name: "Thomas Nyhus", number: 12, position: "Keeper" },
      { name: "Tommy Refsdal", number: 3, position: "Forsvar" },
      { name: "Espen Refsdal", number: 4, position: "Forsvar" },
      { name: "Inocentiu Pavlicu", number: 9, position: "Angrep" },
      { name: "Sander Kolloen Heimdal", number: null, position: "Ukjent" },
      { name: "Vetle Stian Haustveit", number: null, position: "Ukjent" },
      { name: "Albert Haustveit", number: 2, position: "Ukjent" },
      { name: "Tobias Haustveit Vøllestad", number: 5, position: "Ukjent" },
      { name: "Einar Alexander Voje Odden", number: 7, position: "Ukjent" },
      { name: "Simen Løyte Solheim", number: 10, position: "Ukjent" },
    ],
  },
  {
    clubSlug: "seljord",
    teamName: "Seljord",
    division: "6. divisjon",
    players: [
      { name: "Remi Edvin Berg Nerbø", number: null, position: "Keeper" },
      { name: "Roar Slinde", number: null, position: "Forsvar" },
      { name: "Øyvind Oland", number: null, position: "Midtbane" },
      { name: "Martin Listaul", number: 14, position: "Midtbane" },
      { name: "Marius Greiner", number: 15, position: "Midtbane" },
      { name: "Torbjørn Sigstad", number: 20, position: "Angrep" },
      { name: "Harald Lauvik Gjelstad", number: 3, position: "Ukjent" },
      { name: "Simon Carl Valentin Jändel", number: 5, position: "Ukjent" },
      { name: "Noah Lie Kasin", number: 6, position: "Ukjent" },
      { name: "Jan Marcus Hjertås", number: 9, position: "Ukjent" },
      { name: "Svenn Bakken Braun", number: 11, position: "Ukjent" },
      { name: "Tollef Haugen", number: 12, position: "Ukjent" },
    ],
  },
  {
    clubSlug: "bamble",
    teamName: "Bamble",
    division: "6. divisjon",
    players: [
      { name: "Remi Holmen", number: null, position: "Forsvar" },
      { name: "Anders Kittilsen", number: null, position: "Forsvar" },
      { name: "Per Øyvind Svarstad", number: null, position: "Forsvar" },
      { name: "Marcus Olsen", number: null, position: "Midtbane" },
      { name: "Jørund Ingebretsen", number: null, position: "Midtbane" },
      { name: "Marius Westby Olsen", number: null, position: "Ukjent" },
      { name: "Henrik Jarl Haukedal", number: null, position: "Ukjent" },
      { name: "Jan Fredrik Eliassen Nilsen", number: null, position: "Ukjent" },
      { name: "Sindre Nafstad Sandvei", number: null, position: "Ukjent" },
      { name: "Stian Kolberg", number: null, position: "Ukjent" },
    ],
  },
  // 7. DIVISJON
  {
    clubSlug: "afoss",
    teamName: "Åfoss",
    division: "7. divisjon",
    players: [
      { name: "Christoffer Skagsoset", number: 1, position: "Keeper" },
      { name: "Knut Ufs", number: 3, position: "Forsvar" },
      { name: "Simen Sjøstrøm Andersen", number: 5, position: "Forsvar" },
      { name: "Wojciech Michal Plich", number: 6, position: "Forsvar" },
      { name: "Bendik Kallåk Ringdal", number: 16, position: "Forsvar" },
      { name: "Henrik Solli Jensen", number: 8, position: "Midtbane" },
      { name: "Steffen Skyer", number: 11, position: "Midtbane" },
      { name: "Andreas Rønning", number: 24, position: "Midtbane" },
      { name: "Petter Skifjeld", number: 7, position: "Angrep" },
      { name: "Osman Zulquarnain", number: 9, position: "Angrep" },
      { name: "Marius Solli Jensen", number: 10, position: "Angrep" },
      { name: "Adrian Norén", number: 13, position: "Angrep" },
      { name: "Marius Skyer", number: 14, position: "Angrep" },
    ],
  },
  {
    clubSlug: "stridsklev",
    teamName: "Stridsklev",
    division: "7. divisjon",
    players: [
      { name: "Jonas Budal Kostamo", number: 1, position: "Keeper" },
      { name: "Casper Wågene", number: 2, position: "Forsvar" },
      { name: "Christian Meyer-Lund", number: 3, position: "Forsvar" },
      { name: "Mats Bjelland", number: 4, position: "Forsvar" },
      { name: "Jesper Hauksand Dalen", number: 5, position: "Forsvar" },
      { name: "Daniel André Navestad", number: 6, position: "Forsvar" },
      { name: "Vetle Mørch Tvedt", number: 7, position: "Midtbane" },
      { name: "Mats Knutsen", number: 8, position: "Midtbane" },
      { name: "Herman Martinius Romberg", number: 10, position: "Midtbane" },
      { name: "Adrian Nathaniel Andersen", number: 9, position: "Angrep" },
      { name: "Sebastian Andrés Sivertsen", number: 11, position: "Angrep" },
      { name: "Thomas Enger", number: 13, position: "Angrep" },
      { name: "Siver Safin Fattah", number: 17, position: "Angrep" },
      { name: "Mansoor Dilsoz", number: 18, position: "Angrep" },
      { name: "Ruben Seterdal", number: 24, position: "Angrep" },
    ],
  },
  {
    clubSlug: "heddal",
    teamName: "Heddal",
    division: "6. divisjon",
    players: [
      { name: "Petter Kaasa", number: null, position: "Keeper" },
      { name: "Anders Bogen Hegna", number: null, position: "Midtbane" },
      { name: "Olav Aase", number: null, position: "Angrep" },
      { name: "Hans Einar Elnes", number: null, position: "Angrep" },
      { name: "Lars Bakkåker Grini", number: 10, position: "Angrep" },
      { name: "Berat Keser", number: null, position: "Ukjent" },
      { name: "Stian Solberg", number: null, position: "Ukjent" },
      { name: "Pål Espen Øygarden", number: null, position: "Ukjent" },
      { name: "Håkon Bakken", number: null, position: "Ukjent" },
      { name: "Gard André Hagen", number: null, position: "Ukjent" },
    ],
  },
  {
    clubSlug: "nome",
    teamName: "Nome",
    division: "6. divisjon",
    players: [
      { name: "Jacob Gjervik Juliussen", number: null, position: "Ukjent" },
      { name: "Tom Roar Jensen", number: null, position: "Ukjent" },
      { name: "Marius Sandstå Saga", number: null, position: "Ukjent" },
      { name: "Henrik Moen Strand", number: null, position: "Ukjent" },
      { name: "Tommy Strand", number: 5, position: "Ukjent" },
      { name: "Lukasz Federowicz", number: 6, position: "Ukjent" },
      { name: "Johannes Gjervik Juliussen", number: 7, position: "Ukjent" },
      { name: "Sander Nygård", number: 9, position: "Ukjent" },
      { name: "Jon Vegar Løvgren", number: 10, position: "Ukjent" },
      { name: "Dardan Smaili", number: 11, position: "Ukjent" },
    ],
  },
  {
    clubSlug: "siljan",
    teamName: "Siljan",
    division: "6. divisjon",
    players: [
      { name: "Arne Markus Thøgersen", number: null, position: "Ukjent" },
      { name: "Sondre Aleksander Norheim", number: null, position: "Ukjent" },
      { name: "Isak Øverbø", number: null, position: "Ukjent" },
      { name: "Magnus Austad", number: null, position: "Ukjent" },
      { name: "Martin Kløverød", number: null, position: "Ukjent" },
      { name: "Vegar Holte-Høines", number: null, position: "Ukjent" },
      { name: "Jørgen Holmberg Johnsen", number: null, position: "Ukjent" },
      { name: "Martin Hagen", number: null, position: "Ukjent" },
      { name: "Lucas Auran", number: null, position: "Ukjent" },
    ],
  },
  {
    clubSlug: "sauherad",
    teamName: "Sauherad",
    division: "6. divisjon",
    players: [
      { name: "Markus Matland", number: null, position: "Ukjent" },
      { name: "Aleksander Landsverk", number: null, position: "Ukjent" },
      { name: "Ole Martin Sundsvalen", number: null, position: "Ukjent" },
      { name: "Daniel Flåtin Kaasa", number: null, position: "Ukjent" },
      { name: "Stian Landsverk", number: null, position: "Ukjent" },
      { name: "Roger Smedshammer", number: null, position: "Ukjent" },
      { name: "Morten Vale Wang", number: null, position: "Ukjent" },
      { name: "Kristian Holdnes Johnsen", number: null, position: "Ukjent" },
      { name: "Tobias Flathus Hansen", number: null, position: "Ukjent" },
      { name: "Jens Arve Arnesen", number: null, position: "Ukjent" },
    ],
  },
];

export function getSquadsForClub(clubSlug: string): TeamSquad[] {
  return squads.filter((s) => s.clubSlug === clubSlug);
}
